spring.application.name=artnest


spring.datasource.url=jdbc:postgresql://artnest-dev.c1ucw646q6iu.ap-south-1.rds.amazonaws.com:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=5WI4Krq1miiMLaiPnfh4

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=M5oZqQJ1SFx78cVNfNBCpIS34dNwoH0K2R0s6ERw1xpyMkrsSon3XB5SSxyQGewlkFcmH8JM7FZ3xo453siN0A==
